server.port=8080
spring.main.banner-mode=off
logging.level.root=INFO

# H2 in-memory datasource for local development
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Let Hibernate create/update schema for dev; change for production
spring.jpa.hibernate.ddl-auto=update

# Expose H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
